# Site settings
title: Bydas Blog
header-img: img/home-bg.jpg
email: shendabiao@icloud.com
description: "Done is better than perfec!"
baseurl: ""
url: ""
twitter_username:
github_username:  Bydas
facebook_username:
weibo_username:
zhihu_username: 小沈同学

# Build settings
markdown: kramdown

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
  
# Duoshuo settings
duoshuo_username: das
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true
 # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 169816b0df64b2c157a76cec431a3375
